name: 'Simple Pull Request GitHub Action'
description: 'Creates Pull Request after running specified command.'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  token:
    description: GitHub Token to create a pull request
    required: true
  branch_main_name:
    description: Main branch name
    required: false
  branch_pr_name:
    description: Changes branch name
    required: false
  commit_message:
    description: Git commit message
    required: false
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/scripts/pre-command.sh ${{ inputs.branch_pr_name }}
      shell: bash
    - run: ${{ github.action_path }}/scripts/post-command.sh ${{ inputs.token }} ${{ inputs.commit_message }} ${{ inputs.branch_main_name }} ${{ inputs.branch_pr_name }}
      shell: bash
