name: 'Simple Pull Request GitHub Action'
description: 'Creates Pull Request after running specified command.'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  command:
    description: Command to execute
    required: true
  token:
    description: GitHub Token to create a pull request
    required: true
  branch_main_name:
    description: Main branch name
    required: false
  branch_pr_name:
    description: Changes branch name
    required: false
  path:
    description: Path to the directory where command will be executed
    required: false
  commit_message:
    description: Git commit message
    required: false
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}pre-command.sh ${{ inputs.path }}
      shell: bash
    - run: ${{ github.action_path }}command.sh ${{ inputs.command }} ${{ inputs.path }}
      shell: bash
    - run: ${{ github.action_path }}post-command.sh ${{ inputs.token }} ${{ inputs.commit_message }} ${{ inputs.branch_main_name }} ${{ inputs.branch_pr_name }} ${{ inputs.path }}
      shell: bash
