name: Dependencies update

on:
  schedule:
    - cron: '0/60 * * * *'

jobs:
  npm-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: packages/npm-dependencies/pnpm-lock.yaml

      - name: Installing modules
        run: cd packages && cd npm-dependencies && pnpm install

      - name: Updating dependencies
        run: cd packages && cd npm-dependencies && pnpm exec npm-check-updates -u --target minor

      - name: Installing modules
        run: cd packages && cd npm-dependencies && pnpm install

      - name: Creating PR
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch_main_name: "'main'"
          branch_pr_name: "'npm-dependencies'"
          commit_message: "'chore(dependencies): updated automatically'"
